### ISSUE TITLE
Internal CLR Error (Running in sandboxie)

### ISSUE THREAD

**Issue by ro5490** [ncrypted-dev/Fishy#4]
![image](https://github.com/user-attachments/assets/d096f856-c35b-4c38-a42b-781ce55279f4)

Unsure why but after a while of a player being in the server, this happens, will try and debug and post more info

**Comment by ro5490** [comment]
Seems to happen outside of sandboxie too
![image](https://github.com/user-attachments/assets/8c10a837-f72c-4892-8248-eef79ae411db)

**Comment by ro5490** [comment]
![image](https://github.com/user-attachments/assets/710e0570-0329-4857-945b-1bf3a06b9dc2)

**Comment by ncrypted-dev** [comment]
Thanks for the report - I will try to reproduce it once I am back home later!

**Comment by ncrypted-dev** [comment]
Hey, so quick update from me:

I’ve reproduced the issue and suspect it’s related to the Webserver plugin, though I’m not 100% certain yet. For now, I recommend avoiding the Webserver plugin.

I’m testing some more plugins to confirm if the issue lies with .dll loading or the Webserver NuGet package itself. Meanwhile, I’ve released a new x64 build with the latest patches and the Webserver plugin temporarily removed.

**Comment by Kaliumhexacyanoferrat** [comment]
This exit code is related to an `ExecutionEngineException` which indicates a heap garbage collection issue which is usually caused by unmanaged code. The web server does not contain unmanaged code and I have no reports regarding such issues yet - nevertheless if there is an easier way to reproduce this I can have a look.

You can also try to swap `GenHTTP.Core` with `GenHTTP.Core.Kestrel` which is fully compatible but uses a different webserver engine underneath. If the issue does no longer occur this would be a hint.

Additionally: If you rely on x64 libs and you have an Any CPU configuration, you should change this to x64 as well.

**Comment by ncrypted-dev** [comment]
Hey @Kaliumhexacyanoferrat thank you for the input from your side. 

I still didn't have enough time to investigate the issue thoroughly, but I will try the Kestrel Engine tomorrow to see if that works better. 
The crash usually occurs after 10-15 minutes of the web server running, but in some rare cases, it could run longer.

(Probably not related to this issue, but I have also seen some issues with the parser of the GenHTTP Server, where malformed requests could lead to parsing exceptions - This was when I had the server running through a proxy and some external web scrapers/bots sent random requests)

The two most likely points of failure are currently either the compiling of the .dll into a single file (using Costura/Fody) or the loading of the webserver plugin .dll at server startup.

Either way, I hope to have it figured out soon and if I can't get the plugin system working in the next few days, the webserver will be implemented directly into the main program for now, to see if that provides a more stable experience.

**Comment by Kaliumhexacyanoferrat** [comment]
If there is some sort of memory management problem within the application, running a web server will more likely cause it to happen / show as servers have a lot of internal caches and buffers which allocate and sometimes fragment memory. Would indeed be interesting whether embedding the server causes the issue to go away. If there is anything I can support you with just let me know 😉

Regarding the request parser exceptions: Those are intended and do not indicate a engine failure. Maybe they could be a little bit more silent during operation.

**Comment by ncrypted-dev** [comment]
@ro5490 I might have finally found the origin of the issue. Once I have confirmed that it runs stable, I will publish a new release with the webserver enabled again.

Sorry that it took so long, but that was rather a complex issue to debug - I hope to have the new version up by tomorrow evening.

**Comment by ro5490** [comment]
Niceee, glad you where able to find the issue tho, I couldnt figure it out on my end xD

**Comment by Kaliumhexacyanoferrat** [comment]
Me neither, well done! \o/

**Comment by ncrypted-dev** [comment]
I have tested the fix a bit more, and it seems to be working fine for me - The New Release has been uploaded, so this issue is closed for now.

If there are still any problems, feel free to reopen the issue or make a new one :)
